# nixpacks.toml

[phases.install]
cmds = [
  "composer install --no-dev --prefer-dist --no-interaction",
  "npm ci"
]

[phases.build]
# Compila assets y luego elimina node_modules para que no se copie al contenedor final
cmds = [
  "node ./node_modules/vite/bin/vite.js build",
  "rm -rf node_modules"
]

[start]
cmd = "heroku-php-apache2 public/"
